library(rockchalk)
library(ggplot2)
library(tikzDevice)
setwd("~/Documents/sigcse/CS_Course_Data_Analysis/SIGSCE")
df_2017 <- read.csv("cs35_2017.csv")
df_2016 <- read.csv("cs35_2016.csv")
df <- rbind(df_2017, df_2016)

df$Major <- combineLevels(df$Major, c("French", "Spanish", "Studio Art", "Media Studies"),"Art, Language, Media")
#df$Major <- combineLevels(df$Major, c("Linguistics & Cog. Sci.", "Linguistics", "Cognitive Science"), "Linguistics & Cog. Sci.")
df$Major <- combineLevels(df$Major, c("Biology", "Biochemistry", "Chemistry", "Environmental Analysis", "Molecular Biology", "Physics", "Neuroscience", "Science & Management"), "Natural Sciences")
df$Major <- combineLevels(df$Major, c("Public Policy-Politics", "Politics", "International Relations", "Government", "Political Studies", 
                                      "Environ., Econ., Politic", "Phil., Politics, Econ.", "Politics, Phil, Economic", "Philosophy"), "Politics, IR, Philosophy")
df$Major <- combineLevels(df$Major, c("Economics", "Economics - Accounting", "Mathematical Economics"), "Economics")
df$Major <- combineLevels(df$Major, c("Computer Science", "Computer Science & Math", "Mathematics"), "CS & Math")
df$Major <- combineLevels(df$Major, c("Psychology", "Sociology", "Science Tech & Society", "Linguistics & Cog. Sci.", "Linguistics", "Cognitive Science"), "Social Sciences")
#df$Major <- combineLevels(df$Major, c("Environ., Econ., Politic", "Phil., Politics, Econ.", "Politics, Phil, Economic", "Philosophy"), "Politics, Philosophy, Econ")
df$Major <- combineLevels(df$Major, c("Undeclared", "Undecided"), "Undeclared")

#Drop Non-Degree Seeking Major and Undeclared
df <- subset(df, df$Major != "Non-Degree Seeking")
df$Major <- factor(df$Major)
cs35_major_freq <- table(df$Major)
ordered_cs35_major_freq <- sort(cs35_major_freq, decreasing = TRUE)
op <- par(mar = c(12,4,2,2) + 0.1)
colors = c("orange", "cyan", "dodgerblue2", "green", "darkslateblue","dodgerblue4", "grey", "grey")
plot <- barplot(ordered_cs35_major_freq, las=2, axisnames = FALSE, col=colors, main="Majors of CS35 Students")
labels <- names(ordered_cs35_major_freq)
text(plot, par("usr")[3], labels = labels, srt = 45, adj = c(1.1,1.1), xpd = TRUE, cex=.9)
par(op)

tikz('cs35-motivations.tex', standAlone = TRUE)
# Import project categories
project_categories_df <- read.csv("CS35_project_categories.csv")
categories <- project_categories_df$Motivation.Category
category_table <- table(categories)
p_table <- prop.table(category_table)
lbls = c("Academic 18\\%","Personal 53\\%", "Technical 29\\%")
colors <- rainbow(6)
pie(p_table,labels=lbls, main="CS35 Final Projects by Motivation", col=colors)
dev.off()